import: definition.yaml

concurrency:
  task:
    # css: 5
    # omnigibson: 4
    minecraft: 4
  agent:
    gpt-4o-2024-05-13: 4

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-4o-2024-05-13
    task:
      # - css
      # - omnigibson
      - minecraft

# output: "outputs/{TIMESTAMP}"
# output: "outputs/css_test"
# output: "outputs/omnigibson"
output: "outputs/minecraft"
