import: definition.yaml

concurrency:
  task:
    omnigibson: 2
  agent:
    gpt-4o-2024-05-13: 4

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      - gpt-4o-2024-05-13
    task:
      - omnigibson

# output: "outputs/{TIMESTAMP}"
output: "outputs/omnigibson"
