omnigibson:
  module: "src.server.tasks.omnigibson.OmniGibson"
  parameters:
    name: "OmniGibson"
    max_round: 100
    available_ports:
      - 12000
      - 12001
      - 12002
      - 12003
      - 12004
      - 12005
      - 12006
      - 12007
    available_devices:
      "0": 1
      "1": 1
      "2": 1
      "3": 1
      "4": 1
      "5": 1
      "6": 1
      "7": 1
    data_dir: "data/omnigibson"
    output_dir: "outputs/omnigibson"
    docker_image: "tianjiezhang/vab_omnigibson:latest"
