name: verifiers-new
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0.1
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.2
  - tk=8.6.13
  - wheel=0.45.1
  - pip:
      - accelerate==1.4.0
      - aiohttp==3.8.5
      - aiolimiter==1.1.0
      - aiosignal==1.3.1
      - airportsdata==20250224
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyio==3.7.1
      - appnope==0.1.3
      - astor==0.8.1
      - asttokens==2.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backcall==0.2.0
      - beartype==0.12.0
      - beautifulsoup4==4.12.2
      - blake3==1.0.4
      - cachetools==5.5.2
      - certifi==2023.7.22
      - cfgv==3.4.0
      - charset-normalizer==3.2.0
      - click==8.1.8
      - cloudpickle==2.2.1
      - cmake==3.31.6
      - comm==0.1.4
      - compressed-tensors==0.9.1
      - contourpy==1.1.1
      - cupy-cuda12x==13.4.0
      - cycler==0.12.1
      - dashscope==1.22.1
      - datasets==3.3.2
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepspeed==0.16.3
      - depyf==0.18.0
      - dill==0.3.7
      - diskcache==5.6.3
      - distlib==0.3.7
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - duckduckgo-search==7.5.0
      - einops==0.8.1
      - email-validator==2.2.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.3
      - execnet==2.0.2
      - executing==2.0.0
      - farama-notifications==0.0.4
      - fastapi==0.115.11
      - fastapi-cli==0.0.7
      - fastjsonschema==2.18.1
      - fastrlock==0.8.3
      - filelock==3.17.0
      - flash-attn==2.7.4.post1
      - fonttools==4.43.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.15.0
      - google-auth==2.26.1
      - google-cloud-aiplatform==1.38.1
      - google-cloud-bigquery==3.14.1
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.11.0
      - google-cloud-storage==2.14.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.0
      - googleapis-common-protos==1.62.0
      - gradio-client==0.5.2
      - greenlet==2.0.2
      - grpc-google-iam-v1==0.13.0
      - grpcio==1.71.0rc2
      - grpcio-status==1.63.0rc1
      - gymnasium==0.29.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.18.0
      - httptools==0.6.4
      - httpx==0.25.0
      - huggingface-hub==0.29.1
      - identify==2.5.30
      - idna==3.4
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - iniconfig==2.0.0
      - interegular==0.3.3
      - ipykernel==6.25.2
      - ipython==8.16.1
      - jedi==0.19.1
      - jinja2==3.1.5
      - jiter==0.8.2
      - joblib==1.3.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0
      - kiwisolver==1.4.5
      - lark==1.2.2
      - lazy-loader==0.4
      - liger-kernel==0.5.4
      - lit==18.1.8
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - lxml==5.3.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistral-common==1.5.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy==0.991
      - mypy-extensions==1.0.0
      - nbclient==0.6.8
      - nbformat==5.9.2
      - nbmake==1.4.6
      - nest-asyncio==1.5.8
      - networkx==3.1
      - ninja==1.11.1.3
      - nltk==3.8.1
      - nodeenv==1.8.0
      - numba==0.60.0
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.65.2
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.14.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==11.1.0
      - platformdirs==3.11.0
      - playwright==1.37.0
      - pluggy==1.3.0
      - pre-commit==3.0.1
      - primp==0.14.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - prompt-toolkit==3.0.39
      - proto-plus==1.26.0
      - protobuf==4.24.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyee==9.0.4
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pytest==7.1.2
      - pytest-asyncio==0.21.1
      - pytest-xdist==3.3.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - ray==2.40.0
      - referencing==0.30.2
      - regex==2023.8.8
      - requests==2.32.3
      - responses==0.18.0
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - rpds-py==0.10.6
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-image==0.22.0
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.2
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - starlette==0.46.0
      - sympy==1.13.1
      - text-generation==0.6.1
      - tifffile==2025.2.18
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - tomli==2.0.1
      - torch==2.5.1+cu124
      - torchaudio==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - tornado==6.3.3
      - tqdm==4.67.1
      - traitlets==5.11.2
      - transformers==4.49.0
      - triton==3.1.0
      - trl==0.16.0.dev0
      - typer==0.15.2
      - types-requests==2.31.0.10
      - types-tqdm==4.66.0.1
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - urllib3==2.0.4
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - verifiers==0.1.0
      - virtualenv==20.24.5
      - vllm==0.7.3
      - wandb==0.19.7
      - watchfiles==1.0.4
      - wcwidth==0.2.8
      - websocket-client==1.8.0
      - websockets==11.0.3
      - xformers==0.0.28.post3
      - xgrammar==0.1.11
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.21.0
